- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      become: yes
      become_user: kube
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: download metrics-server and my repo
      become: yes
      become_user: kube
      shell: git clone https://github.com/kubernetes-incubator/metrics-server.git >> my_app.txt;
             git clone https://github.com/hiakki/kubernetes.git >> my_app.txt
      args:
        chdir: $HOME
        creates: my_app.txt

    - name: updating metrics-server-deployment.yaml
      copy:
        src: /home/kube/kubernetes/metrics-server-deployment.yaml
        dest: /home/kube/metrics-server/deploy/1.8+/
        remote_src: yes
        owner: kube

    - name: Deploying Metrics-Server for HPA
      become: yes
      become_user: kube
      shell: kubectl apply -f metrics-server/deploy/1.8+/ >> metrics_server.txt
      args:
        chdir: $HOME
        creates: metrics_server.txt

