- hosts: workers
  become: yes
  vars_files:
    - /etc/ansible/group_vars/message.yml
  tasks:

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Emptying hostname file of Groups - Workers
      copy:
        content: ""
        dest: /etc/hostname

    - name: Change HOSTNAME of Groups - Workers
      lineinfile:
        dest: /etc/hostname
        regexp: '.*{{ item }}$'
        line: "{{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.workers }}"
      register: reboot_req

    - name: Reboot immediately if there was a change in reboot_req.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot_req is changed

    - name: Wait for the reboot to complete if there was a change in reboot_req.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_req is changed

    - name: output message.
      debug: msg="{{ message }}"

