- hosts: master
  become: yes
  become_user: kube
  gather_facts: false
  tasks:

    - name: Get Master Node's IP
      shell: ifconfig eth0 | grep 'inet ' | awk {'print $2'}
      register: get_ip

    - name: Set Master Node's IP
      set_fact:
        set_ip: "{{ get_ip.stdout_lines[0] }}"

    - name: Changing External IP
      replace:
        path: /home/kube/kubernetes/my_app/nginx_php-fpm_multicontainer_service.yaml
        regexp: '(\s+)192\.168\.1\.7(\s+.*)?$'
        replace: " {{ hostvars['master'].set_ip }}"
        backup: yes

    - name: deploying HPA my_app
      shell: kubectl create -f /home/kube/kubernetes/my_app/
