- hosts: master
  become: yes
  become_user: kube
  gather_facts: false
  tasks:

    - name: Updating External IP in My_App's Service
      replace:
	dest: /home/kube/kubernetes/my_app/nginx_php-fpm_multicontainer_service.yaml
	regexp: '192.168.1.7'
	replace: "{{ hostvars[item].ansible_host }}"
	state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.masters }}"

    - name: deploying HPA my_app
      shell: kubectl create -f /home/kube/kubernetes/my_app/
