- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: 
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
