- hosts: masters
  become: yes
  become_user: kube
  tasks:

    - name: initialize the cluster
      shell: kubeadm init >> configure-master-node1.txt
      args:
        chdir: $HOME/logs
        creates: cluster_initialized1.txt
      ignore_errors: yes

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      become: yes
      become_user: root
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> configure-master-node2.txt
      args:
        chdir: $HOME/logs
        creates: configure-master-node2.txt
