- hosts: master
  become: yes
  become_user: kube
  tasks:

    - name: Deploying Metrics-Server for HPA
      shell: kubectl apply -f https://raw.githubusercontent.com/hiakki/kubernetes/master/metrics-server/components.yaml >> deploy-metrics-server-for-HPA1.txt
      args:
        chdir: $HOME/logs
        creates: deploy-metrics-server-for-HPA1.txt
